version: '3'

services:

selenium-hub:

image: selenium/hub

ports:

- "4442-4444:4442-4444"

networks:

- grid

node-chrome:

image: selenium/node-chromium

environment:

- SE EVENT BUS HOST-selenium-hub

- SE_EVENT_BUS_PUBLISH_PORT=4444

- SE EVENT BUS SUBSCRIBE PORT=4443

networks:

- grid

node-firefox:

image: selenium/node-firefox

environment:

- SE EVENT BUS HOST-selenium-hub

- SE_EVENT_BUS PUBLISH PORT=4442

- SE_EVENT_BUS SUBSCRIBE PORT=4443

networks:

- grid

networks:
	grid:
		driver: bridge